version: '2'
services:
  web:
    image: kprokopenko/yii2-app-basic
    volumes:
      - .:/app
    ports:
      - "8888:80"
    links:
      - mysql-test
      - mysql
  mysql-test:
    image: mysql
    environment:
      - MYSQL_DATABASE=yii2_basic_tests
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  mysql:
      image: mysql
      environment:
        - MYSQL_DATABASE=yii2basic
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci